---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: cache-restore
  image: drillster/drone-volume-cache:latest
  settings:
    mount:
    - /drone/docker
    restore: true
    volumes:
    - dev_drone_cache:/cache

- name: quay.io/jonnrb/egress
  image: plugins/docker
  settings:
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/jonnrb/egress
    storage_path: /drone/docker
    target: egress
    use_cache: true
    username:
      from_secret: quay_username

- name: quay.io/jonnrb/egress-openvpn
  image: plugins/docker
  settings:
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/jonnrb/egress-openvpn
    storage_path: /drone/docker
    target: egress-openvpn
    use_cache: true
    username:
      from_secret: quay_username

- name: cache-rebuild
  image: drillster/drone-volume-cache:latest
  settings:
    mount:
    - /drone/docker
    rebuild: true
    volumes:
    - dev_drone_cache:/cache

...
