---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: cache-restore
  image: drillster/drone-volume-cache:latest
  settings:
    restore: true
    mount:
    - /drone/docker
    volumes:
    - dev_drone_cache:/cache

- name: quay.io/jonnrb/egress
  image: plugins/docker
  settings:
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/jonnrb/egress
    username:
      from_secret: quay_username
    storage_path: /drone/docker
    use_cache: true

- name: quay.io/jonnrb/egress-openvpn
  image: plugins/docker
  settings:
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/jonnrb/egress-openvpn
    username:
      from_secret: quay_username
    storage_path: /drone/docker
    use_cache: true

- name: cache-rebuild
  image: drillster/drone-volume-cache:latest
  settings:
    rebuild: true
    mount:
    - /drone/docker
    volumes:
    - dev_drone_cache:/cache

...
