---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: cache-restore
  image: drillster/drone-volume-cache:latest
  settings:
    mount:
    - /drone/docker
    restore: true

- name: quay.io/jonnrb/egress
  image: plugins/docker
  settings:
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/jonnrb/egress
    storage_path: /drone/docker
    target: egress
    use_cache: true
    username:
      from_secret: quay_username

- name: quay.io/jonnrb/egress-openvpn
  image: plugins/docker
  settings:
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/jonnrb/egress-openvpn
    storage_path: /drone/docker
    target: egress-openvpn
    use_cache: true
    username:
      from_secret: quay_username

- name: cache-rebuild
  image: drillster/drone-volume-cache:latest
  settings:
    mount:
    - /drone/docker
    rebuild: true

- name: notify-slack
  image: plugins/slack
  settings:
    channel: dev
    webhook:
      from_secret: slack_webhook
  when:
    status:
    - success
    - failure

volumes:
- name: cache
  host:
    path: "/mnt/disk1/@drone-cache:/cache"

...
