---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: egress-test
rules:
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: egress-test
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: egress-test
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: egress-test
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: egress-test
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: egress-test-router
  annotations:
    k8s.v1.cni.cncf.io/networks: default/default,default/test
spec:
  serviceAccountName: egress-test
  containers:
  - name: router
    image: egress:latest
    imagePullPolicy: Never
    args:
    - -logtostderr
    - -v=3
    - -c
    - sleep 10
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
    volumeMounts:
    - name: podinfo
      mountPath: /etc/podinfo
      readOnly: true
    - name: config
      mountPath: /etc/config
      readOnly: true
  volumes:
  - name: podinfo
    downwardAPI:
      items:
      - path: attachments
        fieldRef:
          fieldPath: metadata.annotations['k8s.v1.cni.cncf.io/networks-status']
  - name: config
    configMap:
      name: egress-test-router-config
      items:
      - key: egress.json
        path: egress.json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: egress-test-router-config
data:
  egress.json: |
    {
      "lanNetwork": "default/test",
      "uplinkNetwork": "default/default"
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: egress-test-client
  annotations:
    k8s.v1.cni.cncf.io/networks: test
spec:
  containers:
  - name: client
    image: busybox
    command: ["sh", "-c"]
    args:
    - sleep 10000
  volumes:
  - name: podinfo
    downwardAPI:
      items:
        - path: attachments
          fieldRef:
            fieldPath: metadata.annotations['k8s.v1.cni.cncf.io/networks-status']
  - name: config
    configMap:
      name: egress-test-router-config
      items:
      - key: egress.json
        path: egress.json
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: test
spec:
  config: |
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "kube-test",
      "ipam": {
        "type": "host-local",
        "ranges": [ [ {
          "subnet": "10.11.11.0/24",
          "rangeStart": "10.11.11.100",
          "rangeEnd": "10.11.11.200",
          "gateway": "10.11.11.1"
        } ] ],
        "routes": [ {"dst": "0.0.0.0/0"} ]
      }
    }
...
